import Foundation
import Models
import Networking
import Observation

@MainActor
@Observable
public final class ProfileSetupModel {
    public enum Phase: Equatable, Sendable {
        case idle
        case saving
        case failed(String)
    }

    public static let maximumBioLength = 300

    public var name: String
    public var bio = ""
    public private(set) var pickedPhoto: Data?
    public private(set) var phase: Phase = .idle

    private let auth: any AuthService
    private let media: any MediaService
    private let onSaved: (Account) -> Void

    public init(
        account: Account,
        auth: any AuthService,
        media: any MediaService,
        onSaved: @escaping (Account) -> Void
    ) {
        self.auth = auth
        self.media = media
        self.onSaved = onSaved
        name = Self.looksAutoGenerated(account.displayName) ? "" : account.displayName
        bio = account.bio ?? ""
    }

    static func looksAutoGenerated(_ displayName: String) -> Bool {
        displayName.contains(where: \.isNumber) && !displayName.contains(" ")
    }

    public var canSave: Bool {
        !name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && bio.count <= Self.maximumBioLength
            && phase != .saving
    }

    public var remainingBioCharacters: Int {
        Self.maximumBioLength - bio.count
    }

    public func choose(_ imageData: Data) {
        pickedPhoto = imageData
    }

    public func save() async {
        guard canSave else { return }
        phase = .saving

        do {
            var avatarMediaID: UUID?
            if let pickedPhoto {
                avatarMediaID = try await media.uploadAvatar(pickedPhoto)
            }

            let trimmedBio = bio.trimmingCharacters(in: .whitespacesAndNewlines)
            let account = try await auth.updateProfile(
                ProfileEdit(
                    displayName: name.trimmingCharacters(in: .whitespacesAndNewlines),
                    bio: trimmedBio.isEmpty ? nil : trimmedBio,
                    avatarMediaID: avatarMediaID
                )
            )

            phase = .idle
            onSaved(account)
        } catch {
            phase = .failed(
                (error as? GathrError)?.userFacingMessage ?? "Your profile could not be saved."
            )
        }
    }
}
